### ISSUE TITLE
 Object reference error while loading unmanaged components

### ISSUE THREAD

**Issue by v22arvind** [aboodh95/SolutionLayerRemoval#1]
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at SolutionLayerRemoval.SolutionLayerRemovalControl.<>c.<LoadComponentsDefinitions>b__4_0(RetrieveMultipleResponse x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SolutionLayerRemoval.SolutionLayerRemovalControl.LoadComponentsDefinitions(RunWorkerCompletedEventArgs resultArgs)
   at XrmToolBox.Extensibility.Worker.<>c__DisplayClass4_0.<WorkAsync>b__0(Object s, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)

**Comment by aboodh95** [comment]
@v22arvind ,

Can I know the version of the Environment you are working on it

**Comment by v22arvind** [comment]
CRM 2016, 8.2 - on premise setup.
Any other info you need?

**Comment by aboodh95** [comment]
No, thanks for the details, uniformity the API calls that made in the tool is only supported for V9 and up as the features of removing the layers was only introduced in the latest version
