### ISSUE TITLE
Error when pressing Load Unmanaged Components

### ISSUE THREAD

**Issue by ericsstoll** [aboodh95/SolutionLayerRemoval#3]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at SolutionLayerRemoval.SolutionLayerRemovalControl.<>c.<LoadComponentsDefinitions>b__4_0(RetrieveMultipleResponse x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SolutionLayerRemoval.SolutionLayerRemovalControl.LoadComponentsDefinitions(RunWorkerCompletedEventArgs resultArgs)
   at XrmToolBox.Extensibility.Worker.<>c__DisplayClass4_0.<WorkAsync>b__0(Object s, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
XrmToolBox
    Assembly Version: 1.2020.6.40
    Win32 Version: 1.2020.6.40
    CodeBase: file:///C:/Users/eric/OneDrive/PortableApps/XrmToolbox/XrmToolBox.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4220.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
XrmToolBox.Extensibility
    Assembly Version: 1.2020.6.40
    Win32 Version: 1.2020.6.40
    CodeBase: file:///C:/Users/eric/OneDrive/PortableApps/XrmToolbox/XrmToolBox.Extensibility.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.IdentityModel
    Assembly Version: 3.5.0.0
    Win32 Version: 6.1.7601.24479
    CodeBase: file:///C:/Users/eric/OneDrive/PortableApps/XrmToolbox/Microsoft.IdentityModel.DLL
----------------------------------------
System.IO.Compression.FileSystem
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression.FileSystem/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.FileSystem.dll
----------------------------------------
XrmToolBox.PluginsStore
    Assembly Version: 1.2020.6.40
    Win32 Version: 1.2020.6.40
    CodeBase: file:///C:/Users/eric/OneDrive/PortableApps/XrmToolbox/XrmToolBox.PluginsStore.DLL
----------------------------------------
NuGet.Core
    Assembly Version: 2.14.0.832
    Win32 Version: 2.14.0.832
    CodeBase: file:///C:/Users/eric/OneDrive/PortableApps/XrmToolbox/NuGet.Core.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.3.23909
    CodeBase: file:///C:/Users/eric/OneDrive/PortableApps/XrmToolbox/Newtonsoft.Json.DLL
----------------------------------------
McTools.Xrm.Connection
    Assembly Version: 1.2020.5.33
    Win32 Version: 1.2020.5.33
    CodeBase: file:///C:/Users/eric/OneDrive/PortableApps/XrmToolbox/McTools.Xrm.Connection.DLL
----------------------------------------
McTools.Xrm.Connection.WinForms
    Assembly Version: 1.2020.5.33
    Win32 Version: 1.2020.5.33
    CodeBase: file:///C:/Users/eric/OneDrive/PortableApps/XrmToolbox/McTools.Xrm.Connection.WinForms.DLL
----------------------------------------
Microsoft.Xrm.Sdk
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.45.329
    CodeBase: file:///C:/Users/eric/OneDrive/PortableApps/XrmToolbox/Microsoft.Xrm.Sdk.DLL
----------------------------------------
Microsoft.Xrm.Sdk.Workflow
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.45.329
    CodeBase: file:///C:/Users/eric/OneDrive/PortableApps/XrmToolbox/Microsoft.Xrm.Sdk.Workflow.DLL
----------------------------------------
Microsoft.Crm.Sdk.Proxy
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.45.329
    CodeBase: file:///C:/Users/eric/OneDrive/PortableApps/XrmToolbox/Microsoft.Crm.Sdk.Proxy.DLL
----------------------------------------
Microsoft.Xrm.Tooling.Connector
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.0.51
    CodeBase: file:///C:/Users/eric/OneDrive/PortableApps/XrmToolbox/Microsoft.Xrm.Tooling.Connector.DLL
----------------------------------------
Microsoft.Xrm.Tooling.Ui.Styles
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.0.51
    CodeBase: file:///C:/Users/eric/OneDrive/PortableApps/XrmToolbox/Microsoft.Xrm.Tooling.Ui.Styles.DLL
----------------------------------------
Microsoft.Xrm.Tooling.CrmConnectControl
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.0.51
    CodeBase: file:///C:/Users/eric/OneDrive/PortableApps/XrmToolbox/Microsoft.Xrm.Tooling.CrmConnectControl.DLL
----------------------------------------
Microsoft.IdentityModel.Clients.ActiveDirectory
    Assembly Version: 5.2.7.0
    Win32 Version: 5.2.7.0
    CodeBase: file:///C:/Users/eric/OneDrive/PortableApps/XrmToolbox/Microsoft.IdentityModel.Clients.ActiveDirectory.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Assembly Version: 3.0.6.0
    Win32 Version: 3.0.6.0
    CodeBase: file:///C:/Users/eric/OneDrive/PortableApps/XrmToolbox/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking.ThemeVS2015
    Assembly Version: 3.0.6.0
    Win32 Version: 3.0.6.0
    CodeBase: file:///C:/Users/eric/OneDrive/PortableApps/XrmToolbox/WeifenLuo.WinFormsUI.Docking.ThemeVS2015.DLL
----------------------------------------
ScintillaNET
    Assembly Version: 3.6.3.0
    Win32 Version: 3.6.3.0
    CodeBase: file:///C:/Users/eric/OneDrive/PortableApps/XrmToolbox/ScintillaNET.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.1.1.3
    Win32 Version: 4.6.26907.01
    CodeBase: file:///C:/Users/eric/OneDrive/PortableApps/XrmToolbox/System.Net.Http.DLL
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
McTools.StopAdvertisement
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/eric/OneDrive/PortableApps/XrmToolbox/McTools.StopAdvertisement.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.ComponentModel.Composition
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
AccessSecurityRoles
    Assembly Version: 1.2020.9.10
    Win32 Version: 1.2020.9.10
    CodeBase: file:///C:/USERS/ERIC/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/ACCESSSECURITYROLES.DLL
----------------------------------------
AuditHistoryRollBack
    Assembly Version: 2020.9.9.1
    Win32 Version: 2020.09.09.1
    CodeBase: file:///C:/USERS/ERIC/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/AUDITHISTORYROLLBACK.DLL
----------------------------------------
BDK.XrmToolBox.RecycleBin
    Assembly Version: 1.2019.7.1
    Win32 Version: 1.2019.7.1
    CodeBase: file:///C:/USERS/ERIC/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/BDK.XRMTOOLBOX.RECYCLEBIN.DLL
----------------------------------------
Carfup.XTBPlugins.DeltaStepsBetweenEnvironments
    Assembly Version: 1.2019.11.12
    Win32 Version: 1.2019.11.12
    CodeBase: file:///C:/USERS/ERIC/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/CARFUP.XTBPLUGINS.DELTASTEPSBETWEENENVIRONMENTS.DLL
----------------------------------------
CRMP.XTBPlugin.SystemComparer
    Assembly Version: 1.2020.1.27
    Win32 Version: 1.2020.1.27
    CodeBase: file:///C:/USERS/ERIC/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/CRMP.XTBPLUGIN.SYSTEMCOMPARER.DLL
----------------------------------------
CRMSolutionExplorer
    Assembly Version: 1.2020.5.16
    Win32 Version: 1.2020.5.16
    CodeBase: file:///C:/USERS/ERIC/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/CRMSOLUTIONEXPLORER.DLL
----------------------------------------
Develop1.XrmTBPlugin.RibbonWorkbench2016
    Assembly Version: 3.1.392.1
    Win32 Version: 3.1.392.1
    CodeBase: file:///C:/USERS/ERIC/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DEVELOP1.XRMTBPLUGIN.RIBBONWORKBENCH2016.DLL
----------------------------------------
DynCrmExp.Deduplicator
    Assembly Version: 1.2020.3.18
    Win32 Version: 1.2020.03.18
    CodeBase: file:///C:/USERS/ERIC/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/DYNCRMEXP.DEDUPLICATOR.DLL
----------------------------------------
Innofactor.XTB.DateTimeBehaviorUtility
    Assembly Version: 1.2016.10.2
    Win32 Version: 1.2016.10.2
    CodeBase: file:///C:/USERS/ERIC/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/INNOFACTOR.XTB.DATETIMEBEHAVIORUTILITY.DLL
----------------------------------------
ManagedSolutionSitemapFixer
    Assembly Version: 1.0.2.0
    Win32 Version: 1.0.2.0
    CodeBase: file:///C:/USERS/ERIC/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MANAGEDSOLUTIONSITEMAPFIXER.DLL
----------------------------------------
MarkMpn.Sql4Cds
    Assembly Version: 2.3.0.0
    Win32 Version: 2.3.0.0
    CodeBase: file:///C:/USERS/ERIC/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MARKMPN.SQL4CDS.DLL
----------------------------------------
MsCrmTools.SiteMapEditor
    Assembly Version: 1.2019.5.12
    Win32 Version: 1.2019.5.12
    CodeBase: file:///C:/USERS/ERIC/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SITEMAPEDITOR.DLL
----------------------------------------
MsCrmTools.SolutionImport
    Assembly Version: 1.2016.8.23
    Win32 Version: 1.2016.8.23
    CodeBase: file:///C:/USERS/ERIC/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/MSCRMTOOLS.SOLUTIONIMPORT.DLL
----------------------------------------
Rappen.XTB.FXB
    Assembly Version: 1.2020.7.3
    Win32 Version: 1.2020.07.003
    CodeBase: file:///C:/USERS/ERIC/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/RAPPEN.XTB.FXB.DLL
----------------------------------------
Rappen.XTB.PTV
    Assembly Version: 1.2019.12.1
    Win32 Version: 1.2019.12.001
    CodeBase: file:///C:/USERS/ERIC/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/RAPPEN.XTB.PTV.DLL
----------------------------------------
RegisterPlugInSteps
    Assembly Version: 1.2018.12.10
    Win32 Version: 1.2018.12.10
    CodeBase: file:///C:/USERS/ERIC/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/REGISTERPLUGINSTEPS.DLL
----------------------------------------
Ryr.SolutionHistory
    Assembly Version: 2.3.0.0
    Win32 Version: 2.3.0
    CodeBase: file:///C:/USERS/ERIC/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/RYR.SOLUTIONHISTORY.DLL
----------------------------------------
Ryr.XrmToolBox.SolutionInstaller
    Assembly Version: 1.2018.5.5
    Win32 Version: 1.2018.5.5
    CodeBase: file:///C:/USERS/ERIC/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/RYR.XRMTOOLBOX.SOLUTIONINSTALLER.DLL
----------------------------------------
Savants.ManageSolution
    Assembly Version: 1.2019.11.20
    Win32 Version: 1.2019.11.20
    CodeBase: file:///C:/USERS/ERIC/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/SAVANTS.MANAGESOLUTION.DLL
----------------------------------------
SlimSolution
    Assembly Version: 1.0.0.11
    Win32 Version: 1.0.0.11
    CodeBase: file:///C:/USERS/ERIC/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/SLIMSOLUTION.DLL
----------------------------------------
SolutionLayerRemoval
    Assembly Version: 1.0.1.4
    Win32 Version: 1.0.1.4
    CodeBase: file:///C:/USERS/ERIC/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/SOLUTIONLAYERREMOVAL.DLL
----------------------------------------
SolutionManager
    Assembly Version: 1.2018.1.4
    Win32 Version: 1.2018.1.4
    CodeBase: file:///C:/USERS/ERIC/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/SOLUTIONMANAGER.DLL
----------------------------------------
Xrm.Sdk.PluginRegistration.Merged
    Assembly Version: 3.2020.5.2
    Win32 Version: 3.2020.05.002
    CodeBase: file:///C:/USERS/ERIC/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/XRM.SDK.PLUGINREGISTRATION.DLL
----------------------------------------
XRMSolutionDependencyChecker
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0
    CodeBase: file:///C:/USERS/ERIC/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/XRMSOLUTIONDEPENDENCYCHECKER.DLL
----------------------------------------
System.ServiceModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
MetadataViewProxies_e7211ee8-ab8d-4523-87e3-802abc1227b6
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4220.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4220.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Data.Services.Client
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.Services.Client/v4.0_4.0.0.0__b77a5c561934e089/System.Data.Services.Client.dll
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4220.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4220.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Web.Services
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Web.Services/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.Services.dll
----------------------------------------
System.Runtime.Caching
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Caching/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.Caching.dll
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Deployment
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4240.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Deployment/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Deployment.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.ServiceModel.Channels
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Channels/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Channels.dll
----------------------------------------
System.IdentityModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IdentityModel/v4.0_4.0.0.0__b77a5c561934e089/System.IdentityModel.dll
----------------------------------------
System.IdentityModel.Selectors
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IdentityModel.Selectors/v4.0_4.0.0.0__b77a5c561934e089/System.IdentityModel.Selectors.dll
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Octokit
    Assembly Version: 0.29.0.0
    Win32 Version: 1.2018.5.5
    CodeBase: file:///C:/USERS/ERIC/APPDATA/ROAMING/MSCRMTOOLS/XRMTOOLBOX/PLUGINS/RYR.XRMTOOLBOX.SOLUTIONINSTALLER.dll
----------------------------------------
System.Web.Extensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Web.Extensions/v4.0_4.0.0.0__31bf3856ad364e35/System.Web.Extensions.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by aboodh95** [comment]
Hi @ericsstoll , Can I know the environment version you are trying to work on it

**Comment by samhajjar1** [comment]
Encountered the same issue, I'm on an on-premise environment Dynamics 365 Version 1612 (9.0.31.7)
